package it.bohdloss.tfmg.content.electricity.base;

import com.simibubi.create.api.equipment.goggles.IHaveGoggleInformation;
import com.simibubi.create.api.equipment.goggles.IHaveHoveringInformation;
import com.simibubi.create.foundation.blockEntity.SmartBlockEntity;
import com.simibubi.create.foundation.item.TooltipHelper;
import com.simibubi.create.foundation.sound.SoundScapes;
import com.simibubi.create.foundation.utility.CreateLang;
import com.simibubi.create.infrastructure.config.AllConfigs;
import it.bohdloss.tfmg.DebugStuff;
import it.bohdloss.tfmg.content.electricity.BlockResistanceValues;
import it.bohdloss.tfmg.content.electricity.ElectricalCluster;
import it.bohdloss.tfmg.content.electricity.ElectricalNetworkManager;
import net.createmod.catnip.data.Iterate;
import net.createmod.catnip.lang.FontHelper;
import net.createmod.catnip.platform.CatnipServices;
import net.minecraft.ChatFormatting;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.Set;

public class ElectricData implements IHaveGoggleInformation, IHaveHoveringInformation {
    public final SmartBlockEntity owner;
    protected boolean initialized;

    public ElectricEffectHandler effects;
    public boolean preventConnection;
    public boolean wasMoved;
    public boolean syncNextTick;
    public boolean connectNextTick;
    public int flickerTally;

    // Compiled electric values
    public float frequency;
    public float voltage;
    public boolean shortCircuit;
    public float lastWattsConsumed;
    public float lastWattsProvided;

    public ElectricData(SmartBlockEntity owner) {
        IElectric $ = (IElectric) owner; // Throw exception immediately if not the case :)
        this.owner = owner;
        this.effects = new ElectricEffectHandler(this);
    }

    /*
     *  Public Interface
     */

    public final void clear() {
        frequency = 0;
        voltage = 0;
        shortCircuit = false;
        lastWattsConsumed = 0;
        lastWattsProvided = 0;
    }

    public final boolean isAlternating() {
        return frequency > 0;
    }

    /// Ohms
    public float getResistance() {
        return (float) BlockResistanceValues.getResistance(getPowerConfigKey());
    }

    /// Ohms
    public float getGeneratorResistance() {
        return (float) BlockResistanceValues.getGeneratorResistance(getPowerConfigKey());
    }

    /// Watts
    public final float getConsumedWattage() {
        return lastWattsConsumed;
    }

    /// Watts
    public final float getGeneratedWattage() {
        return lastWattsProvided;
    }

    /// Amps
    public final float getConsumedAmps() {
        return voltage == 0 ? 0 : lastWattsConsumed / voltage;
    }

    /// Amps
    public final float getGeneratedAmps() {
        float voltage = getGeneratedVoltage();
        return voltage == 0 ? 0 : lastWattsConsumed / voltage;
    }

    /// Volts
    public final float getVoltage() {
        return shortCircuit() ? 0f : voltage;
    }

    public final boolean shortCircuit() {
        return shortCircuit;
    }

    /// Hertz
    public final float getFrequency() {
        return frequency;
    }

    /**
     * Return the frequency generated by this component. Any value higher than zero changes the behavior to that of an
     * alternating current generator. Only has any effects if this component is a generator (I.E. getGeneratedVoltage() > 0)
     */
    public float getGeneratorFrequency() {
        return 0;
    }

    /**
     * Return the voltage generated by this component. Any value higher than zero changes the behavior to that of an
     * electric generator
     */
    public float getGeneratedVoltage() {
        return 0;
    }

    public final void notifyVoltageChange(float previousVoltage) {
        if(previousVoltage == voltage) {
            return;
        }

        onVoltageChange(previousVoltage);
        boolean fromOrToZero = (previousVoltage == 0) != (voltage == 0);
        boolean directionSwap = !fromOrToZero && Math.signum(previousVoltage) != Math.signum(voltage);
        if (fromOrToZero || directionSwap) {
            flickerTally += 5;
        }
        owner.setChanged();
    }

    /// Find neighboring electric entities and merge their networks into one.
    public final void attach() {
        connectNextTick = false;

        ElectricalNetworkManager.getInstance(getLevel()).add(getBlockPos());
    }

    public final void debug() {
//        DebugStuff.show("Init: " + initialized);
        if(getLevel() != null) {
            ElectricalCluster network = ElectricalNetworkManager.getInstance(getLevel()).clusterFor(getBlockPos());
            if(network != null) {
                DebugStuff.show("Network: " + network.id + " -> @" + Integer.toHexString(network.hashCode()));
            } else {
                DebugStuff.show("Network: " + network);
            }
//            DebugStuff.show("We are on " + (getLevel().isClientSide() ? "Client" : "Server"));
        }
//        DebugStuff.show("Frequency: " + frequency);
        DebugStuff.show("Voltage: " + voltage);
        DebugStuff.show("Production: " + lastWattsProvided);
        DebugStuff.show("Consumption: " + lastWattsConsumed);
//        DebugStuff.show("Total Production: " + totalNetworkProduction);
//        DebugStuff.show("Total Usage: " + totalNetworkUsage);
    }

    /// Remove this component from its network, possibly splitting it into multiple networks.
    protected final void detach() {
        ElectricalNetworkManager.getInstance(getLevel()).remove(getBlockPos());

        // At this point this component belongs to a network with a single component (itself)
        syncNextTick = true;
    }

    /**
     * Called when the voltage changes as observed by this component. The value of `voltage` has already been updated
     * at this point.
     */
    public void onVoltageChange(float previousVoltage) { }

    /*
     *  Connectivity
     */

    /**
     * Positions added to `neighbors` will be checked for a connection.
     */
    public void getPotentialNeighbors(Set<BlockPos> neighbors) {
        for(Direction direction : Iterate.directions) {
            if(hasConnectorTowards(direction)) {
                neighbors.add(getBlockPos().relative(direction));
            }
        }
    }

    /**
     * Positions added to `outputs` will be marked as output connections when calculating the voltage modification
     * of this component. Must be a subset of the potential neighbors.
     *
     * This doesn't necessarily indicate the direction of flow, all it does is give an arbitrary directionality
     * to the voltage multiplier.
     */
    public void getOutputConnections(Set<BlockPos> outputs) {}

    /// In a voltage altering component, the voltage going from the input to the output will be multiplied by this value
    public float getInputOutputVoltageMultiplier() { return 1; }

    /// In a voltage altering component, the voltage going from the output to the input will be multiplied by this value
    public float getOutputInputVoltageMultiplier() { return 1; }

    /// In a voltage altering component, the frequency going from the input to the output will be multiplied by this value
    public float getInputOutputFrequencyMultiplier() { return 1; }

    /// In a voltage altering component, the frequency going from the output to the input will be multiplied by this value
    public float getOutputInputFrequencyMultiplier() { return 1; }

    /**
     * Convenience method to determine the possible connection points of a simple electrical component.
     * If you need more complex logic for determining connections, consider overriding `getPotentialNeighbors` instead.
     */
    public boolean hasConnectorTowards(Direction direction) {
        return false;
    }

    /*
     *  Duties of the electric block entity
     */

    public final void tick() {
        if(isClient()) {
            CatnipServices.PLATFORM.executeOnClientOnly(() -> this::tickAudio);
            return;
        }

        if(!initialized) {
            initialized = true;
            syncNextTick = true;
            return;
        }

        if(connectNextTick && !preventConnection) {
            attach();
        }

        effects.tick();
        preventConnection = false;

        if(flickerTally != 0) {
            flickerTally--;
        }

        if(syncNextTick) {
           syncNextTick = false;

           float previousVoltage = voltage;
           ElectricalNetworkManager.getInstance(getLevel()).sync(getBlockPos());
           notifyVoltageChange(previousVoltage);

           notifyUpdate();
        }
    }

    public final void lazyTick() { }

    public final void remove() {
        if(isClient()) {
            return;
        }

        detach();
    }

    public final CompoundTag write(HolderLookup.Provider registries, boolean clientPacket) {
        CompoundTag tag = new CompoundTag();

        tag.putFloat("Frequency", frequency);
        tag.putFloat("Voltage", voltage);
        tag.putBoolean("ShortCircuit", shortCircuit);
        tag.putFloat("LastWattsConsumed", lastWattsConsumed);
        tag.putFloat("LastWattsProvided", lastWattsProvided);

        return tag;
    }

    public final void read(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        boolean shortCircuitBefore = shortCircuit();
        clear();
        if(wasMoved) {
            return;
        }

        frequency = tag.getFloat("Frequency");
        voltage = tag.getFloat("Voltage");
        shortCircuit = tag.getBoolean("ShortCircuit");
        lastWattsConsumed = tag.getFloat("LastWattsConsumed");
        lastWattsProvided = tag.getFloat("LastWattsProvided");

        if (clientPacket && (shortCircuitBefore != shortCircuit() && voltage != 0)) {
            effects.triggerShortCircuitEffect();
        }
    }

    @OnlyIn(Dist.CLIENT)
    public void tickAudio() {
        float componentVoltage = getVoltage();
        if (componentVoltage == 0) {
            return;
        }
        float pitch = Mth.clamp((componentVoltage / 256f) + .45f, .85f, 1f);

        SoundScapes.play(SoundScapes.AmbienceGroup.KINETIC, getBlockPos(), pitch); // TODO electric hum
    }

    /*
     *  Methods for convenience
     */

    public final boolean isClient() {
        return getLevel() == null || getLevel().isClientSide();
    }

    public final Level getLevel() {
        return owner.getLevel();
    }

    public final @NotNull BlockPos getBlockPos() {
        return owner.getBlockPos();
    }

    public final @NotNull BlockState getBlockState() {
        return owner.getBlockState();
    }

    public final void notifyUpdate() {
        owner.notifyUpdate();
    }

    public Block getPowerConfigKey() {
        return getBlockState().getBlock();
    }

    public final boolean isGenerator() {
        return getGeneratedVoltage() > 0;
    }

    public static void switchToBlockState(Level world, BlockPos pos, BlockState state) {
        if (world.isClientSide)
            return;

        BlockEntity blockEntity = world.getBlockEntity(pos);
        BlockState currentState = world.getBlockState(pos);
        boolean isElectric = blockEntity instanceof IElectric;

        if (currentState == state)
            return;
        if (blockEntity == null || !isElectric) {
            world.setBlock(pos, state, 3);
            return;
        }

        IElectric electricBlockEntity = (IElectric) blockEntity;
        ElectricData data = electricBlockEntity.getElectricData();
        if (state.getBlock() instanceof IElectricBlock && !((IElectricBlock) state.getBlock()).areStatesElectricallyEquivalent(currentState, state)) {
            data.detach();
            data.connectNextTick = true;
        }

        world.setBlock(pos, state, 3);
    }

    /*
     *  UI
     */

    @Override
    public boolean addToTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        if (shortCircuit() && AllConfigs.client().enableOverstressedTooltip.get()) {
            CreateLang.translate("gui.stressometer.shorted")
                    .style(ChatFormatting.GOLD)
                    .forGoggles(tooltip);
            Component hint = CreateLang.translateDirect("gui.contraptions.network_shorted");
            List<Component> cutString = TooltipHelper.cutTextComponent(hint, FontHelper.Palette.GRAY_AND_WHITE);
            for (Component component : cutString)
                CreateLang.builder()
                        .add(component
                                .copy())
                        .forGoggles(tooltip);
            return true;
        }

        return false;
    }

    @Override
    public boolean addToGoggleTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        boolean added = false;

        if (!Mth.equal(lastWattsConsumed, 0)) {
            CreateLang.translate("gui.goggles.electric_stats")
                    .forGoggles(tooltip);

            CreateLang.translate("tooltip.powerConsumed")
                    .style(ChatFormatting.GRAY)
                    .forGoggles(tooltip);

            CreateLang.number(lastWattsConsumed)
                    .translate("generic.unit.power")
                    .style(ChatFormatting.AQUA)
                    .space()
                    .add(CreateLang.translate("gui.goggles.at_current_voltage")
                            .style(ChatFormatting.DARK_GRAY))
                    .forGoggles(tooltip, 1);

            added |= true;
        }

        if (!Mth.equal(lastWattsProvided, 0)) {

            CreateLang.translate("gui.goggles.electric_generator_stats")
                    .forGoggles(tooltip);
            CreateLang.translate("tooltip.powerProvided")
                    .style(ChatFormatting.GRAY)
                    .forGoggles(tooltip);

            CreateLang.number(lastWattsProvided)
                    .translate("generic.unit.power")
                    .style(ChatFormatting.AQUA)
                    .space()
                    .add(CreateLang.translate("gui.goggles.at_current_voltage")
                            .style(ChatFormatting.DARK_GRAY))
                    .forGoggles(tooltip, 1);

            added |= true;
        }

        return added;
    }
}
