package it.bohdloss.tfmg.content.electricity.base;

import com.simibubi.create.api.equipment.goggles.IHaveGoggleInformation;
import com.simibubi.create.api.equipment.goggles.IHaveHoveringInformation;
import com.simibubi.create.foundation.blockEntity.SmartBlockEntity;
import com.simibubi.create.foundation.item.TooltipHelper;
import com.simibubi.create.foundation.sound.SoundScapes;
import com.simibubi.create.foundation.utility.CreateLang;
import com.simibubi.create.infrastructure.config.AllConfigs;
import it.bohdloss.tfmg.DebugStuff;
import it.bohdloss.tfmg.content.electricity.BlockResistanceValues;
import it.bohdloss.tfmg.content.electricity.ElectricalNetwork;
import it.bohdloss.tfmg.content.electricity.ElectricalNetworkManager;
import net.createmod.catnip.data.Iterate;
import net.createmod.catnip.lang.FontHelper;
import net.createmod.catnip.platform.CatnipServices;
import net.minecraft.ChatFormatting;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;

public class ElectricData implements IHaveGoggleInformation, IHaveHoveringInformation {
    public final SmartBlockEntity owner;
    public Long network;
    protected boolean initialized;
    public long updates;

    public ElectricEffectHandler effects;
    public boolean preventConnection;
    public boolean wasMoved;
    public boolean syncNextTick;
    public boolean connectNextTick;
    public int flickerTally;

    // Compiled electric values
    public float frequency;
    public float voltage;
    public float totalNetworkUsage;
    public float totalNetworkProduction;
    public float lastAmpsConsumed;
    public float lastAmpsProvided;

    // Cache so that we don't allocate lists every time
    protected List<BlockPos> positions;
    protected List<ElectricalNetwork> networks;

    public ElectricData(SmartBlockEntity owner) {
        IElectric $ = (IElectric) owner; // Throw exception immediately if not the case :)
        this.owner = owner;
        this.effects = new ElectricEffectHandler(this);
    }

    protected void initCache() {
        if(positions == null) {
            positions = new ArrayList<>(6);
        }
        if(networks == null) {
            networks = new ArrayList<>(6);
        }
    }

    /*
     *  Public Interface
     */

    public final void clear() {
        frequency = 0;
        voltage = 0;
        totalNetworkUsage = 0;
        totalNetworkProduction = 0;
        lastAmpsConsumed = 0;
        lastAmpsProvided = 0;
    }

    public final boolean isAlternating() {
        return frequency > 0;
    }

    /// Watts
    public final float getConsumedPower() {
        return getConsumedCurrent() * getVoltage();
    }

    /// Watts
    public final float getGeneratedPower() {
        return getGeneratedCurrent() * getGeneratedVoltage();
    }

    /// Ohms
    public float getResistance() {
        return (float) BlockResistanceValues.getResistance(getPowerConfigKey());
    }

    /// Ohms
    public float getGeneratorResistance() {
        return (float) BlockResistanceValues.getGeneratorResistance(getPowerConfigKey());
    }

    /// Amps
    public final float getConsumedCurrent() {
        return lastAmpsConsumed;
    }

    /// Amps
    public final float getGeneratedCurrent() {
        return lastAmpsProvided;
    }

    /// Volts
    public final float getVoltage() {
        return shortCircuit() ? 0f : voltage;
    }

    public final boolean shortCircuit() {
        return totalNetworkUsage > totalNetworkProduction;
    }

    /**
     * Return the voltage generated by this component. Any value higher than zero changes the behavior to that of an
     * electric generator
     */
    public float getGeneratedVoltage() {
        return 0;
    }

    public final ElectricalNetwork fetchNetwork() {
        return ElectricalNetworkManager.getNetworkById(getLevel(), network);
    }

    public final void notifyVoltageChange(float previousVoltage) {
        if(previousVoltage == voltage) {
            return;
        }

        onVoltageChange(previousVoltage);
        boolean fromOrToZero = (previousVoltage == 0) != (voltage == 0);
        boolean directionSwap = !fromOrToZero && Math.signum(previousVoltage) != Math.signum(voltage);
        if (fromOrToZero || directionSwap) {
            flickerTally += 5;
        }
        owner.setChanged();
    }

    /// Find neighboring electric entities and merge their networks into one.
    public final void attach() {
        initCache();

        connectNextTick = false;

        positions.clear();
        networks.clear();
        getPotentialNeighbors(positions);

        // Find potential connected neighbors and then check if they reciprocate
        for(BlockPos neighbor : positions) {
            if (neighbor.equals(getBlockPos())) {
                continue;
            }
            if (!(getLevel().getBlockEntity(neighbor) instanceof IElectric be)) {
                continue;
            }
            ElectricData neighborData = be.getElectricData();

            // If both components are part of the same network, they are already connected
            if(neighborData.network.equals(network)) {
                continue;
            }

            neighborData.initCache();
            neighborData.positions.clear();
            neighborData.getPotentialNeighbors(neighborData.positions);

            // Connection!
            if (neighborData.positions.contains(getBlockPos())) {
                // Register connection both ways
                ElectricalNetwork neighborNetwork = neighborData.fetchNetwork();
                neighborNetwork.addConnection(neighbor, getBlockPos());
                ElectricalNetwork thisNetwork = fetchNetwork();
                thisNetwork.addConnection(getBlockPos(), neighbor);

                // Add network so that it may be merged later
                networks.add(neighborNetwork);
            }
        }
        networks.add(this.fetchNetwork());

        // Find the biggest network and move all components of the other networks
        ElectricalNetwork winner = null;
        for(ElectricalNetwork checking : networks) {
            if(winner == null || checking.members.size() > winner.members.size()) {
                winner = checking;
            }
        }

        if(winner == null) {
            return;
        }

        // This deletes the smaller networks, and updates the network ids of loaded block entities
        for(ElectricalNetwork loser : networks) {
            winner.absorb(loser);
        }

        positions.clear();
        networks.clear();

        winner.step();
    }

    public final void debug() {
        DebugStuff.show("Init: " + initialized);
        DebugStuff.show("Network: " + network + (fetchNetwork() == null ? " (unreachable)" : ""));
        if(getLevel() != null) {
            DebugStuff.show("We are on " + (getLevel().isClientSide() ? "Client" : "Server"));
        }
        DebugStuff.show("Frequency: " + frequency);
        DebugStuff.show("Voltage: " + voltage);
        DebugStuff.show("Production: " + lastAmpsProvided);
        DebugStuff.show("Consumption: " + lastAmpsConsumed);
        DebugStuff.show("Total Production: " + totalNetworkProduction);
        DebugStuff.show("Total Usage: " + totalNetworkUsage);
    }

    /// Remove this component from its network, possibly splitting it into multiple networks.
    /// FIXME better split algorithm
    public final void detach() {
        // Split network
        ElectricalNetwork previousNetwork = fetchNetwork();
        previousNetwork.splitNetwork(getBlockPos());

        // At this point this component belongs to a network with a single component (itself)
        syncNextTick = true;
    }

    /**
     * Called when the voltage changes as observed by this component. The value of `voltage` has already been updated
     * at this point.
     */
    public void onVoltageChange(float previousVoltage) { }

    /*
     *  Connectivity
     */

    /**
     * Positions added to `neighbors` will be checked for a connection.
     */
    public void getPotentialNeighbors(List<BlockPos> neighbors) {
        for(Direction direction : Iterate.directions) {
            if(hasConnectorTowards(direction)) {
                neighbors.add(getBlockPos().relative(direction));
            }
        }
    }

    /**
     * Convenience method to determine the possible connection points of a simple electrical component.
     * If you need more complex logic for determining connections, consider overriding `getPotentialNeighbors` instead.
     */
    public boolean hasConnectorTowards(Direction direction) {
        return false;
    }

    /*
     *  Duties of the electric block entity
     */

    public final void initializeNetwork() {
        if(isClient()) {
            return;
        }

        if(network == null) {
            // Means this has just been placed, generate a new network, then try to connect
            ElectricalNetwork newNetwork = ElectricalNetworkManager.createNewNetwork(getLevel());
            newNetwork.addComponent(this);
            network = newNetwork.id;
            updates = newNetwork.updates;

            connectNextTick = true;
            syncNextTick = true;
            clear();
        } else {
            // Use the current network id as a cache searching for a network

            // This is expected to be slower when placing a new electrical component merges multiple networks
            // into one, causing the network id to change for a component that is still unloaded (this one),
            // as it will trigger a linear search through networks to find it
            ElectricalNetwork electricalNetwork = ElectricalNetworkManager.findFor(this, network);
            if(electricalNetwork == null) {
                connectNextTick = true;
                ElectricalNetwork newNetwork = ElectricalNetworkManager.createNewNetwork(getLevel()); // No hits -> create a new network
                newNetwork.addComponent(this);
                network = newNetwork.id;
                updates = newNetwork.updates;

                connectNextTick = true;
                syncNextTick = true;
                clear();
            } else {
                network = electricalNetwork.id;
                updates = electricalNetwork.updates;

                connectNextTick = false;
                syncNextTick = true;
                clear();
            }
        }
        owner.notifyUpdate();
    }

    public final void tick() {
        if(isClient()) {
            CatnipServices.PLATFORM.executeOnClientOnly(() -> this::tickAudio);
            return;
        }

        if(!initialized) {
            initialized = true;
            initializeNetwork();
            return;
        }

        if(connectNextTick && !preventConnection) {
            attach();
        }

        effects.tick();
        preventConnection = false;

        if(flickerTally != 0) {
            flickerTally--;
        }

        ElectricalNetwork network = fetchNetwork();
        if(syncNextTick || network.updates != updates) {
           syncNextTick = false;

           float previousVoltage = voltage;
           network.syncComponent(this);
           notifyVoltageChange(previousVoltage);

           notifyUpdate();
        }
    }

    public final void lazyTick() { }

    public final void remove() {
        if(isClient()) {
            return;
        }

        detach();
        fetchNetwork().removeComponent(getBlockPos());
        fetchNetwork().owner.networks.remove(network);
    }

    public final CompoundTag write(HolderLookup.Provider registries, boolean clientPacket) {
        CompoundTag tag = new CompoundTag();

        if(network != null) {
            tag.putLong("Network", network);
        }

        tag.putFloat("Frequency", frequency);
        tag.putFloat("Voltage", voltage);
        tag.putFloat("TotalNetworkUsage", totalNetworkUsage);
        tag.putFloat("TotalNetworkProduction", totalNetworkProduction);
        tag.putFloat("LastAmpsConsumed", lastAmpsConsumed);
        tag.putFloat("LastAmpsProvided", lastAmpsProvided);

        return tag;
    }

    public final void read(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        boolean shortCircuitBefore = shortCircuit();
        clear();
        if(wasMoved) {
            return;
        }

        if(tag.contains("Network")) {
            network = tag.getLong("Network");
        } else {
            network = null;
        }

        frequency = tag.getFloat("Frequency");
        voltage = tag.getFloat("Voltage");
        totalNetworkUsage = tag.getFloat("TotalNetworkUsage");
        totalNetworkProduction = tag.getFloat("TotalNetworkProduction");
        lastAmpsConsumed = tag.getFloat("LastAmpsConsumed");
        lastAmpsProvided = tag.getFloat("LastAmpsProvided");

        if (clientPacket && (shortCircuitBefore != shortCircuit() && voltage != 0)) {
            effects.triggerShortCircuitEffect();
        }
    }

    @OnlyIn(Dist.CLIENT)
    public void tickAudio() {
        float componentVoltage = getVoltage();
        if (componentVoltage == 0) {
            return;
        }
        float pitch = Mth.clamp((componentVoltage / 256f) + .45f, .85f, 1f);

        SoundScapes.play(SoundScapes.AmbienceGroup.KINETIC, getBlockPos(), pitch); // TODO electric hum
    }

    /*
     *  Methods for convenience
     */

    public final boolean isClient() {
        return getLevel() == null || getLevel().isClientSide();
    }

    public final Level getLevel() {
        return owner.getLevel();
    }

    public final @NotNull BlockPos getBlockPos() {
        return owner.getBlockPos();
    }

    public final @NotNull BlockState getBlockState() {
        return owner.getBlockState();
    }

    public final void notifyUpdate() {
        owner.notifyUpdate();
    }

    public Block getPowerConfigKey() {
        return getBlockState().getBlock();
    }

    public final boolean isGenerator() {
        return getGeneratedVoltage() > 0;
    }

    public static void switchToBlockState(Level world, BlockPos pos, BlockState state) {
        if (world.isClientSide)
            return;

        BlockEntity blockEntity = world.getBlockEntity(pos);
        BlockState currentState = world.getBlockState(pos);
        boolean isElectric = blockEntity instanceof IElectric;

        if (currentState == state)
            return;
        if (blockEntity == null || !isElectric) {
            world.setBlock(pos, state, 3);
            return;
        }

        IElectric electricBlockEntity = (IElectric) blockEntity;
        ElectricData data = electricBlockEntity.getElectricData();
        if (state.getBlock() instanceof IElectricBlock && !((IElectricBlock) state.getBlock()).areStatesElectricallyEquivalent(currentState, state)) {
            data.detach();
            data.connectNextTick = true;
        }

        world.setBlock(pos, state, 3);
    }

    /*
     *  UI
     */

    @Override
    public boolean addToTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        if (shortCircuit() && AllConfigs.client().enableOverstressedTooltip.get()) {
            CreateLang.translate("gui.stressometer.shorted")
                    .style(ChatFormatting.GOLD)
                    .forGoggles(tooltip);
            Component hint = CreateLang.translateDirect("gui.contraptions.network_shorted");
            List<Component> cutString = TooltipHelper.cutTextComponent(hint, FontHelper.Palette.GRAY_AND_WHITE);
            for (Component component : cutString)
                CreateLang.builder()
                        .add(component
                                .copy())
                        .forGoggles(tooltip);
            return true;
        }

        return false;
    }

    @Override
    public boolean addToGoggleTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        boolean added = false;

        if (!Mth.equal(lastAmpsConsumed, 0)) {
            CreateLang.translate("gui.goggles.electric_stats")
                    .forGoggles(tooltip);

            CreateLang.translate("tooltip.powerConsumed")
                    .style(ChatFormatting.GRAY)
                    .forGoggles(tooltip);

            CreateLang.number(lastAmpsConsumed)
                    .translate("generic.unit.current")
                    .style(ChatFormatting.AQUA)
                    .space()
                    .add(CreateLang.translate("gui.goggles.at_current_voltage")
                            .style(ChatFormatting.DARK_GRAY))
                    .forGoggles(tooltip, 1);

            added |= true;
        }

        if (!Mth.equal(lastAmpsProvided, 0)) {

            CreateLang.translate("gui.goggles.electric_generator_stats")
                    .forGoggles(tooltip);
            CreateLang.translate("tooltip.powerProvided")
                    .style(ChatFormatting.GRAY)
                    .forGoggles(tooltip);

            CreateLang.number(lastAmpsProvided)
                    .translate("generic.unit.current")
                    .style(ChatFormatting.AQUA)
                    .space()
                    .add(CreateLang.translate("gui.goggles.at_current_voltage")
                            .style(ChatFormatting.DARK_GRAY))
                    .forGoggles(tooltip, 1);

            added |= true;
        }

        return added;
    }
}
